### ISSUE TITLE
using "/lrs history" crashes the game

### ISSUE THREAD

**Issue by Shurelia** [McPlayHD/LootrunStatistics#21]
after upgrading from v1.0.2 without resetting the mod data causes lrs history command to fail and crash client
(other informations provided on crash log)
[crash-2023-01-11_07.13.36-client.txt](https://github.com/McPlayHD/LootrunStatistics/files/10387715/crash-2023-01-11_07.13.36-client.txt)

**Comment by TomR24** [comment]
Just happened to me as well, crash log says NullPointerException so it's probably caused when the file that stores the mythics is empty (at least it is empty for me)

**Comment by McPlayHD** [comment]
Thansk for the report.

> after upgrading from v1.0.2 without resetting the mod data causes lrs history command to fail and crash client (other informations provided on crash log) [crash-2023-01-11_07.13.36-client.txt](https://github.com/McPlayHD/LootrunStatistics/files/10387715/crash-2023-01-11_07.13.36-client.txt)

Could you maybe send me your `%appdata%\.minecraft\lootrunstatistics\<uuid>\mythicFinds.json` file? There might be some sort of issue with the conversion from the old version.

**Comment by TomR24** [comment]
> Thanks for the report.
> 
> > after upgrading from v1.0.2 without resetting the mod data causes lrs history command to fail and crash client (other informations provided on crash log) [crash-2023-01-11_07.13.36-client.txt](https://github.com/McPlayHD/LootrunStatistics/files/10387715/crash-2023-01-11_07.13.36-client.txt)
> 
> Could you maybe send me your `%appdata%\.minecraft\lootrunstatistics\<uuid>\mythicFinds.json` file? There might be some sort of issue with the conversion from the old version.

My json file only contains `{}`, idk if it's supposed to look like that

**Comment by McPlayHD** [comment]
> My json file only contains {}, idk if it's supposed to look like that

This means that you didn't find a mythic so far. Could you also send me the crash-report if you also get a crash when executing the command?

**Comment by McPlayHD** [comment]
Oh actually it might be an issue when converting from the `chestcountmod` to the `LootrunStatistics` mod if you didn't find any mythics when you used the `chestcountmod`.
You are right @TomR24 my current version expects 
```json
{
  "mythicFinds": []
}
```
instead of
```json
{}
```
this is easily fixable.

**Comment by McPlayHD** [comment]
But it looks like this is not the same issue as the one @Shurelia is currently having, since it actually finds a `MythicFind` for her but it seems like the BoxTitle is in a wrong format. So I'll wait for them to answer before merging the update.

**Comment by McPlayHD** [comment]
So @TomR24 it's very important that you edit the `mythicFinds.json` file manually and put the following into it instead of `{}`:
```json
{
  "mythicFinds": []
}
```
because otherwise if you find a mythic the mythic might not be saved. It won't crash because I took care of any sort of exceptions the mod could throw there but it would just fail to store the mythic in that case.

**Comment by TomR24** [comment]
yep works, ty

**Comment by McPlayHD** [comment]
@Shurelia if this issue is still not fixed after https://github.com/McPlayHD/LootrunStatistics/pull/22 please reopen this issue or create a new one.
